# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5537ca35d3fbad12584c8b7d92b94976a8cbfc78b4ba702e60202f297da7784581501e351ef333889c632b193daa54e4b63aacc0e8b5f8c9ca6c8b27f1c5618b

test:
  secret_key_base: 978a6b03c6abc21a8644508c0317930305db11c617d3dd4cc3c2574dfdf8a661ebecfbe25222027eb22e7e6e27947df0b56d6a6cee170d5494a4937cccc4690a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
